name: SCA GitHub Actions/ Docker workflow

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pytest and flask
        run: pip install --no-cache-dir pytest flask

      - name: Run test
        run: pytest 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}          

      - name: Build and push to DockerHub using prebuilt action
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jonahmary17/mary-sca-ci-cd:latest
